import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex max-w-[800px] justify-center items-center mx-auto flex-col gap-8 px-4 relative`}>
        {children}
      </body>
    </html>
  );
}
